Add `append(rows)` method (without offset) to StreamWriter
googleapis/java-bigquerystorage pull request #1452
Opened 2021-12-22 22:46 UTC by jphalip

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigquerystorage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> ☕️

2021-12-22 22:50 UTC, yirutang approved these changes

2021-12-23 16:12 UTC, stephaniewang526 requested changes
Hi Julien, please update your initial commit to: `feat: support append() without offset in StreamWriter`

2021-12-23 16:38 UTC, tswast commented
@stephaniewang526 Since there are multiple commits, only the PR title needs to be changed.

2021-12-23 19:41 UTC, stephaniewang526 commented
> @stephaniewang526 Since there are multiple commits, only the PR title needs to be changed.

Great to know! Thank you!

2021-12-23 19:41 UTC, stephaniewang526 approved these changes

2021-12-23 19:56 UTC, merged