Feature/numerics
googleapis/java-bigquerystorage pull request #1588
Opened 2022-03-26 12:59 UTC by dark0dave

Introduces #1586 , this allows users to send strings of numerics to the api and have them case properly into the correct numeric type.

2022-03-26 15:37 UTC, dark0dave commented
![image](https://user-images.githubusercontent.com/52840419/160246654-639e6dad-98db-4b46-80f3-f2bb964c178b.png)

2022-03-28 17:11 UTC, stephaniewang526 requested changes
Could you add a unit test for these changes?

2022-03-28 19:27 UTC, dark0dave commented on google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java
> +        if (val instanceof String && ("true".equals(val) || "false".equals(val))) {
Yes. Updated.

2022-03-28 19:29 UTC, dark0dave commented
@stephaniewang526 tests added.

2022-03-29 15:20 UTC, dark0dave commented
@stephaniewang526 let me know if anything else is needed.

2022-03-29 20:44 UTC, stephaniewang526 approved these changes

2022-03-29 20:45 UTC, merged