Adding ExecutorProvider support while creating BigQueryReadClient
googleapis/java-bigquerystorage pull request #2072
Opened 2023-03-30 20:46 UTC by suryasoma

Fixes #2071

2023-04-04 17:56 UTC, nileyadav approved these changes

2023-04-04 18:03 UTC, kmjung approved these changes

2023-04-04 18:06 UTC, kmjung commented
R: @Neenu1995

2023-04-13 20:45 UTC, Neenu1995 requested changes

2023-04-13 20:45 UTC, Neenu1995 commented on google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/EnhancedBigQueryReadStub.java
> +            .setBackgroundExecutorProvider(settings.getBackgroundExecutorProvider());
Can you add IT tests for this addition?

2023-04-14 18:29 UTC, Neenu1995 approved these changes

2023-04-14 19:11 UTC, merged